### ISSUE TITLE
Poor performance?

### ISSUE THREAD

**Issue by uxmaster** [justin-schroeder/arrow-js#93]
I'm very excited about ArrowJS, but I've just came across [benchmark](https://krausest.github.io/js-framework-benchmark/current.html), where ArrowJS is one of the slowest.

On the other hand, your [performance demo](https://www.arrow-js.com/demos/fast-text.html) clearly shows ArrowJS is much faster than Vue.

I'm kind of confused...

**Comment by justin-schroeder** [comment]
Yeah great question. Few things to mention here. First, there are a lot of performance enhancements coming down the pipe that should make most of this a moot point.

Second, js benchmarks is valid, but only partially so. All the results are super juiced — what I mean by that is most of the code written is optimized in a way that realistically people dont write their application code. The vue benchmark, for example, uses memo keys and shallow refs to give the absolute fastest performance possible. This isn’t wrong, because it has to "compete" with a ton of libraries doing the same thing, but in the end, the code isnt really how people write their JS.

The version of arrow benchmarked doesnt even have memokeys (it will in the future just to help with the benchmark tests), so they way it is written is pretty much how you would write code in your own app. There are certainly some operations which arrow is slower at than other libraries. In general fine grained mutations, which is what our demo shows, is quite fast.

In the real world, all of these frameworks are "fast enough" — and the only real bottlenecks you should see are initial paint speeds (which arrow is generally quite good at) and a huge number of dom elements (which any fine grained reactive system is quite good at, including arrow).

Again, when I get some time to refocus my efforts back on arrow I plan roll out a number of significant performance improvements. In the meantime if you are interested in a more performant version you can checkout arrow-refactor-1 and arrow-refactor-2.

Good luck out there ❤️
